version: '2'
services:
  device-modbus:
    container_name: edgex-device-modbus
    environment:
      CLIENTS_CORE_COMMAND_HOST: ${EDGEX_HOST}
      CLIENTS_CORE_COMMAND_PORT: 30082
      CLIENTS_CORE_DATA_HOST: ${EDGEX_HOST}
      CLIENTS_CORE_DATA_PORT: 30080
      CLIENTS_CORE_METADATA_HOST: ${EDGEX_HOST}
      CLIENTS_CORE_METADATA_PORT: 30081
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: ${EDGEX_HOST}
      CLIENTS_SUPPORT_NOTIFICATIONS_PORT: 30060
      CLIENTS_SUPPORT_SCHEDULER_HOST: ${EDGEX_HOST}
      CLIENTS_SUPPORT_SCHEDULER_PORT: 30085
      DATABASES_PRIMARY_HOST: ${EDGEX_HOST}
      DATABASES_PRIMARY_PORT: 30079
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: ${EDGEX_HOST}
      MESSAGEQUEUE_PORT: 30079
      REGISTRY_HOST: ${EDGEX_HOST}
      REGISTRY_PORT: 30850
      SERVICE_HOST: ${DEVICE_HOST}
    hostname: edgex-device-modbus
    image: edgexfoundry/device-modbus-arm64:2.1.0
    command: --cp=consul.http://${EDGEX_HOST}:30850 --registry --confdir=/res
    network_mode: "host"
    ports:
    - 127.0.0.1:59901:59901/tcp
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
