version: '2'
services:
  device-mqtt:
    container_name: edgex-device-mqtt
    environment:
      CLIENTS_CORE_COMMAND_HOST: 192.168.50.13
      CLIENTS_CORE_COMMAND_PORT: 30082
      CLIENTS_CORE_DATA_HOST: 192.168.50.13
      CLIENTS_CORE_DATA_PORT: 30080
      CLIENTS_CORE_METADATA_HOST: 192.168.50.13
      CLIENTS_CORE_METADATA_PORT: 30081
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: 192.168.50.13
      CLIENTS_SUPPORT_NOTIFICATIONS_PORT: 30060
      CLIENTS_SUPPORT_SCHEDULER_HOST: 192.168.50.13
      CLIENTS_SUPPORT_SCHEDULER_PORT: 30085
      DATABASES_PRIMARY_HOST: 192.168.50.13
      DATABASES_PRIMARY_PORT: 30079
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: 192.168.50.13
      MESSAGEQUEUE_PORT: 30079
      MQTTBROKERINFO_HOST: 192.168.50.7
      REGISTRY_HOST: 192.168.50.13
      REGISTRY_PORT: 30850
      SERVICE_HOST: 192.168.50.7
      DEVICE_DEVICESDIR: /custom-config/devices
      DEVICE_PROFILESDIR: /custom-config/profiles
    hostname: edgex-device-mqtt2
    image: edgexfoundry/device-mqtt-arm64:2.0.0
    command: --cp=consul.http://192.168.50.13:30850 --registry --confdir=/res
    network_mode: "host"
#    ports:
#    - 59982:59982/tcp
    volumes:
    - /home/ubuntu/docker-compose-mqtt/custom-config:/custom-config
    read_only: true
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
  mqtt-broker:
    container_name: edgex-mqtt-broker
    hostname: edgex-mqtt-broker
    image: emqx/emqx:latest
    ports:
    - 1883:1883/tcp
    - 18083:18083/tcp
